version: "2"

services:
  engine:
    image: qlikcore/engine:12.612.0
    restart: always
    command: -S AcceptEULA=yes -S DocumentDirectory=/data
    ports:
      - "19076:9076"
    volumes:
      - ./engine/data:/data
